# Generated by Django 3.1.7 on 2021-10-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='xyz', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=12345, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
