# Generated by Django 3.1.7 on 2021-10-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/user_directory'),
        ),
    ]
